# Generated by Django 5.0 on 2023-12-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostGato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha_recate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PostPerro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha_recate', models.DateField()),
            ],
        ),
    ]
