# Generated by Django 5.0 on 2023-12-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgato',
            name='imagen',
            field=models.ImageField(upload_to='media/gatos'),
        ),
        migrations.AlterField(
            model_name='postperro',
            name='imagen',
            field=models.ImageField(upload_to='media/perros'),
        ),
    ]
